redhat-developer/vscode-paver

- src/commons/progressData.ts
- src/configureAssistant.ts
- src/modelServer.ts
- src/ollama/ollamaServer.ts
- src/panels/setupGranitePage.ts
- src/utils/cpUtils.ts
- webviews/src/App.css
- webviews/src/App.tsx
- webviews/src/ModelList.tsx
- webviews/src/ProgressBar.tsx
- fixes #4 
- fixes #24
- fixes #25
> Add progress bar to webview

- webviews/src/App.css
> Use VS Code style variables for button styling

- src/extension.ts
- src/panels/setupGranitePage.ts
> Enable webview livereload in Dev mode

- .vscode/launch.json
- README.md
- USAGE_DATA.md
- package-lock.json
- package.json
- src/configureAssistant.ts
- src/extension.ts
- src/panels/setupGranitePage.ts
- src/telemetry/index.ts
> Add Red Hat Telemetry

- package-lock.json
- package.json
> Update @redhat-developer/vscode-redhat-telemetry to 0.9.0

- .vscode/launch.json
- src/ollama/mockServer.ts
- src/ollama/ollamaServer.ts
- src/panels/setupGranitePage.ts
- webviews/src/App.tsx
- webviews/src/ModelList.tsx
- webviews/src/ProgressBar.tsx
This mock server, can be launched via the `Run Extension w/ Mock Ollama` launch configuration
- resets every time the wizard is shown
- simulates server installation via script or manually
- simulates downloading images at 300MB/s
- can be tweaked to throw errors in specific cases (@neehar18 see TODOs)
> Added mock ollama server

- src/ollama/mockServer.ts
- src/panels/setupGranitePage.ts
- webviews/src/App.tsx
In reference to: https://github.com/redhat-developer/vscode-granite/issues/5
> Add error handling

- webviews/src/App.css
- webviews/src/App.tsx
- webviews/src/ModelList.tsx
- webviews/src/ProgressBar.tsx
- Code changed in App.css, App.tsx, ModelList.tsx and ProgressBar.tsx
- UI Design Changes.
- Dark Mode UI Design Fixes
> setup page theme aware fix

- webviews/src/App.tsx
> Configure 8b models by default

- webviews/src/App.tsx
- webviews/src/ModelList.tsx
- webviews/src/StatusCheck.tsx
- Added keep existing configuration option to all combos.
- disabled button when all combos selected keep existing configuration.
- code changed in App.tsx, ModelList.tsx and StatusCheck.tsx files.
> Added keep existing configuration option to all combos and disabled button when all combos selected keep existing configuration

- src/ollama/ollamaServer.ts
> Don't fail if brew is missing

- webviews/src/App.css
- webviews/src/App.tsx
adding meaningful description for wizard page
> adding meaningful description for wizard page

- README.md
- src/ollama/ollamaServer.ts
> Display 'installing' icon when installing ollama via script/homebrew

- .github/workflows/release.yaml
- package.json
- releng/create-package-insiders-json.js
> Enable releases to Marketplaces

- webviews/src/App.tsx
changing tab model only for 3b and 8b
> changing tab model only for 3b and 8b

- src/ollama/ollamaServer.ts
- src/utils/downloadUtils.ts
- src/utils/fsUtils.ts
> Automatically install Ollama on Windows

- webviews/src/App.css
- webviews/src/App.tsx
set-up Display instructions on how to re-open the wizard
Fixes #91
> set-up Display instructions on how to re-open the wizard

- package.json
- src/configureAssistant.ts
- src/ollama/ollamaServer.ts
- src/panels/setupGranitePage.ts
- src/terminal/terminalCommandRunner.ts
- webviews/index.html
> Remove more Granite Code references. Keep just Granite

- src/configureAssistant.ts
> Use CONTINUE_GLOBAL_DIR env var to find Continue config file

- webviews/src/ModelList.tsx
fixed the issue: dropdown granite models are editable
> fixed the issue: dropdown granite models are editable

- src/configureAssistant.ts
- src/panels/setupGranitePage.ts
- webviews/src/App.css
- webviews/src/App.test.tsx
- webviews/src/App.tsx
Simple Section:
------------
Advanced Section:
> Added the advanced section, for selecting Chat and Tab Completion separately
